[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = {path = "../lib"}
axum = "0.8.8"
clap = {version = "4.5.57", features = ["derive"]}
tokio = {version = "1.49", features = ["full"]}
tower-http = {version = "0.6.8", features = ["fs", "trace"]}
